{
 "title": "Nebula metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{site_name=\"nebula\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nebula_cpu_usage", "legendFormat": "{{ hostname }}" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nebula_memory_usage", "legendFormat": "{{ hostname }}" }
   ]
  }
 ]
}